# Generated by Django 2.2.1 on 2019-05-26 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20190526_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
