# Generated by Django 2.2.1 on 2019-05-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0004_auto_20190526_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
