# Generated by Django 2.2.1 on 2019-05-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0005_text_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
